[build]
builder = "nixpacks"

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/zh-Hant"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
