[build]
builder = "nixpacks"

[deploy]
startCommand = "./scripts/railway-deploy.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
